### ISSUE TITLE
Katello 4.3.0: Bullseye re-sync takes more than 5 hours

### ISSUE THREAD

**Issue by gvde** [pulp/pulp_deb#466] opened 2022-03-30 16:36 UTC
**Version**
Katello 4.3.0, tfm-pulpcore-python3-pulpcore-3.16.6-1.el7.noarch, tfm-pulpcore-python3-pulp-deb-2.16.1-1.el7.noarch
updated from 4.2.2 with pulpcore 3.14

**Describe the bug**
Since upgrading syncing bullseye main repository takes extremely long, more than 5 hours instead of 22 minutes before the upgrade. Tried twice, each sync more than 5 hours. During sync one postgres process is at almost 100% most of the time.

Buster main repository went from 13 minutes to 42 minutes.

**To Reproduce**
Upstream URL http://deb.debian.org/debian bullseye main amd64

**Expected behavior**
Faster sync.

**Additional context**
Foreman community [Katello 4.3.0: Bullseye sync takes more than 5 hours](https://community.theforeman.org/t/katello-4-3-0-bullseye-sync-takes-more-than-5-hours/27880)

**Comment by quba42** [comment] 2022-04-07 07:57
I will have a look at what changed between 2.14 and 2.16 and see if I can reproduce this.

**Comment by quba42** [comment] 2022-04-12 06:57
Some preliminary findings: I can't fully reproduce this. On my Katello 4.3 based machine with pulpcore 3.16.1 and pulp_deb 2.16.1, it took 2h 22min to sync
```
http://ftp.de.debian.org/debian/
bullseye
main non-free
amd64
```
While not exactly great performance this is still a far cry better than what @gvde reported. I also did not observe any busy postgres processes during the sync, only a busy pulp worker process. I can have another look if there is anything suspicious between pulpcore 3.16.1 and 3.16.6, and perhaps I can deploy a Katello 4.1 based machine today, to check the performance drop relative to that. Some performance drop is to be expected, since there is now a lot more edge case handling during sync.

**Comment by gvde** [comment] 2022-04-12 07:22
More than 2 hours or more than hours isn't really that much of a difference for a normal (incremental) sync of a repository. It's just much too long. I have Immediate and Content Only policies set for the repository, so almost everything is already on the server. All what has to be done is to check for changes and download them. I don't really understand what should take 5 hours or even only 2 hours for that.

I have just started the sync again and I see 3 postmaster processes running, one of them at almost 100%. There seem to be a lot of query like this (checked if pg_stat_activity)
```
pulpcore=# explain analyze SELECT "core_content"."pulp_id" FROM "core_content" WHERE ("core_content"."pulp_id" IN ('2b4713ec-30ec-4ff2-9fe4-f9d927062b1a'::uuid, 'e953377c-80e7-4250-9d31-5e4b9d538178'::uuid) AND NOT ("core_content"."pulp_id" IN (SELECT V0."pulp_id" FROM "core_content" V0 INNER JOIN "core_repositorycontent" V1 ON (V0."pulp_id" = V1."content_id") WHERE V1."pulp_id" IN (SELECT U0."pulp_id" FROM "core_repositorycontent" U0 INNER JOIN "core_repositoryversion" U2 ON (U0."version_added_id" = U2."pulp_id") LEFT OUTER JOIN "core_repositoryversion" U3 ON (U0."version_removed_id" = U3."pulp_id") WHERE (U0."repository_id" = '5cf43358-9694-4dc5-a602-be660c479856'::uuid AND U2."number" <= 4 AND NOT (U3."number" <= 4 AND U3."number" IS NOT NULL))))));
                                                                                      QUERY PLAN                                                                                       
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Bitmap Heap Scan on core_content  (cost=71905.68..71913.61 rows=1 width=16) (actual time=1500.427..1507.513 rows=0 loops=1)
   Recheck Cond: (pulp_id = ANY ('{2b4713ec-30ec-4ff2-9fe4-f9d927062b1a,e953377c-80e7-4250-9d31-5e4b9d538178}'::uuid[]))
   Filter: (NOT (hashed SubPlan 1))
   Rows Removed by Filter: 2
   Heap Blocks: exact=2
   ->  Bitmap Index Scan on core_content_pkey  (cost=0.00..8.86 rows=2 width=0) (actual time=0.017..0.018 rows=2 loops=1)
         Index Cond: (pulp_id = ANY ('{2b4713ec-30ec-4ff2-9fe4-f9d927062b1a,e953377c-80e7-4250-9d31-5e4b9d538178}'::uuid[]))
   SubPlan 1
     ->  Gather  (cost=33156.81..71841.40 rows=22167 width=16) (actual time=339.510..1343.925 rows=117239 loops=1)
           Workers Planned: 2
           Workers Launched: 2
           ->  Nested Loop  (cost=32156.81..68624.70 rows=9236 width=16) (actual time=334.659..1338.886 rows=39080 loops=3)
                 ->  Parallel Hash Semi Join  (cost=32156.39..64103.03 rows=9236 width=16) (actual time=334.586..988.881 rows=39080 loops=3)
                       Hash Cond: (v1.pulp_id = u0.pulp_id)
                       ->  Parallel Seq Scan on core_repositorycontent v1  (cost=0.00..31036.77 rows=307477 width=32) (actual time=0.006..273.264 rows=245981 loops=3)
                       ->  Parallel Hash  (cost=32040.94..32040.94 rows=9236 width=16) (actual time=334.258..334.284 rows=39080 loops=3)
                             Buckets: 131072 (originally 32768)  Batches: 1 (originally 1)  Memory Usage: 7328kB
                             ->  Hash Join  (cost=76.36..32040.94 rows=9236 width=16) (actual time=3.146..274.675 rows=39080 loops=3)
                                   Hash Cond: (u0.version_added_id = u2.pulp_id)
                                   ->  Hash Left Join  (cost=38.44..31970.07 rows=12472 width=32) (actual time=1.745..187.707 rows=39080 loops=3)
                                         Hash Cond: (u0.version_removed_id = u3.pulp_id)
                                         Filter: ((u3.number > 4) OR (u3.number IS NULL))
                                         ->  Parallel Seq Scan on core_repositorycontent u0  (cost=0.00..31805.46 rows=48069 width=48) (actual time=0.063..101.662 rows=39080 loops=3)
                                               Filter: (repository_id = '5cf43358-9694-4dc5-a602-be660c479856'::uuid)
                                               Rows Removed by Filter: 206902
                                         ->  Hash  (cost=29.86..29.86 rows=686 width=20) (actual time=1.647..1.657 rows=678 loops=3)
                                               Buckets: 1024  Batches: 1  Memory Usage: 43kB
                                               ->  Seq Scan on core_repositoryversion u3  (cost=0.00..29.86 rows=686 width=20) (actual time=0.013..0.821 rows=678 loops=3)
                                   ->  Hash  (cost=31.58..31.58 rows=508 width=16) (actual time=1.382..1.386 rows=508 loops=3)
                                         Buckets: 1024  Batches: 1  Memory Usage: 32kB
                                         ->  Seq Scan on core_repositoryversion u2  (cost=0.00..31.58 rows=508 width=16) (actual time=0.025..0.776 rows=508 loops=3)
                                               Filter: (number <= 4)
                                               Rows Removed by Filter: 170
                 ->  Index Only Scan using core_content_pkey on core_content v0  (cost=0.42..0.49 rows=1 width=16) (actual time=0.006..0.006 rows=1 loops=117239)
                       Index Cond: (pulp_id = v1.content_id)
                       Heap Fetches: 117239
 Planning Time: 0.853 ms
 Execution Time: 1508.879 ms
(38 rows)

```

According to pg_stat_activity the identical query is on three processes.

In between the phase of postmaster being busy I can see a pulpcore-worker at 100%. So basically, it looks like pulpcore-worker is running 100% than does some database queries which take a couple of seconds and keep one postgres process fully busy.

And that goes for 5 hours syncing a repository which is basically already here...

**Comment by quba42** [comment] 2022-04-12 08:21
Ok, the re-sync/incremental sync is definitely taking to long! It is at 45 min and counting even though very little should have changed since yesterday!

**Comment by gvde** [comment] 2022-04-12 08:55
I have justed checked the task details in katello of the running sync during a couple of minutes.

The only part changing is this:
```
{"message"=>"Associating Content",
       "code"=>"associating.content",
       "state"=>"running",
       "done"=>16871}
```

The number is slowing increasing at a rate of approximately 230 per minute. My previous sync from this morning has a total number of 57352 there. So just taking 57352 at a rate of 230 per minute would account for more than 4 hours runtime...

**Comment by quba42** [comment] 2022-04-12 12:52
Update: Based on the versions I have seen affected by this, I can now say that it is caused by some change to pulp_deb and not by pulpcore.

Fixing this issue is now a top priority, but I cannot yet project when it may be fixed, since I have not yet found the root cause.

**Comment by quba42** [comment] 2022-04-19 09:06
Hypothesis: Insufficient batching of the slow queries might be at least part of the problem.

**Comment by quba42** [comment] 2022-04-19 11:30
On all our internal tests, this mainly appears to affect initial syncs, but not re-syncs (at least not when there are no new packages).

For example: Syncing bullseye main amd64 (58616 packages, 117239 associated content) took an excruciating 30 hours (symptoms exactly as described above) for the initial sync on my test system, but the re-sync took 28 minutes, which is comparable to Pulp 2 re-syncs.

Of course this issue needs to be solved for all cases (sync and re-sync), just posting my observations so far.

**Comment by gvde** [comment] 2022-04-19 12:54
> For example: Syncing bullseye main amd64 (58616 packages, 117239 associated content) took an excruciating 30 hours (symptoms exactly as described above) for the initial sync on my test system, but the re-sync took 28 minutes, which is comparable to Pulp 2 re-syncs.

I haven't tried an initial sync again and I also don't have the durations for pulp 2 resyncs. My observation is only between Katello 4.2 and 4.3 and deb resyncs taking significantly longer. I have no complaints about rpm syncs.

**Comment by quba42** [comment] 2022-04-19 13:51
It looks like this is caused by the following issue in pulpcore: https://github.com/pulp/pulpcore/issues/2557
It should be fixed with the corresponding fix: https://github.com/pulp/pulpcore/pull/2558

**Comment by quba42** [comment] 2022-04-20 06:59
The pulpcore fix is now merged! It will be backported as far as pulpcore 3.16.

**Comment by gvde** [comment] 2022-04-20 08:26
I have just started another sync of bullseye main. Associating content is now at 10939 after 32 minutes. So it seem to be somewhat faster but only maybe factor 2, unlike with katello 4.2/pulpcore 3.14 when it took approx. 22 minutes to finish the sync...

**Comment by gvde** [comment] 2022-04-20 10:46
O.K. Second run. Again 57 minutes. Definitely much better than those 5 hours before. But still 2,5 times what it was before the  upgrade to 4.3.

It's really not quite clear to me why it is that long to begin with. RPM repo syncs with more than 30.000 packages are much faster, less than a minute if nothing has changed.

**Comment by quba42** [comment] 2022-04-21 12:34
Right, I am now closing this issue, since it will really be fixed here: https://github.com/pulp/pulpcore/issues/2557

This does not mean there are no more pulp_deb performance improvements to be had, but those will be worked on under new issues!

**Closed by quba42** 2022-04-21 12:34 UTC
Labels: Triage-Needed
