### ISSUE TITLE
No suitable Package index file found

### ISSUE THREAD

**Issue by knzivid** [pulp/pulp_deb#520] opened 2022-05-05 10:27 UTC
**Version**
pulp-deb                        2.13.0
pulp-file                       1.7.0
pulpcore                        3.13.0

**Describe the bug**

I am synchronizing focal-updates from [no.archive.ubuntu.com](http://no.archive.ubuntu.com). This worked fine until yesterday. I am not sure what changed on no.archive.ubuntu.com.

```
Giving up _run(...) after 1 tries (aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://no.archive.ubuntu.com/ubuntu/dists/focal-updates/universe/binary-amd64/Packages>
06:18:16 Traceback (most recent call last):
  File "/opt/pulp/lib/python3.7/site-packages/rq/worker.py", line 1013, in perform_job
    rv = job.perform()
  File "/opt/pulp/lib/python3.7/site-packages/rq/job.py", line 709, in perform
    self._result = self._execute()
  File "/opt/pulp/lib/python3.7/site-packages/rq/job.py", line 732, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/opt/pulp/lib/python3.7/site-packages/pulp_deb/app/tasks/synchronizing.py", line 122, in synchronize
    DebDeclarativeVersion(first_stage, repository, mirror=mirror).create()
  File "/opt/pulp/lib/python3.7/site-packages/pulpcore/plugin/stages/declarative_version.py", line 149, in create
    loop.run_until_complete(pipeline)
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/pulp/lib/python3.7/site-packages/pulpcore/plugin/stages/api.py", line 225, in create_pipeline
    await asyncio.gather(*futures)
  File "/opt/pulp/lib/python3.7/site-packages/pulpcore/plugin/stages/api.py", line 43, in __call__
    await self.run()
  File "/opt/pulp/lib/python3.7/site-packages/pulp_deb/app/tasks/synchronizing.py", line 321, in run
    filename = _uncompress_artifact(d_content.d_artifacts, relative_dir)
  File "/opt/pulp/lib/python3.7/site-packages/pulp_deb/app/tasks/synchronizing.py", line 355, in _uncompress_artifact
    raise NoPackageIndexFile(relative_dir=relative_dir)
pulp_deb.app.tasks.synchronizing.NoPackageIndexFile: No suitable Package index file found in 'dists/focal-updates/main/binary-amd64'.
```

The mirror has [Packages.gz and Packages.xz](http://no.archive.ubuntu.com/dists/focal-updates/main/binary-amd64/) present, but no Packages. On emailing the maintainer of the mirror, I became aware that missing uncompressed `Packages` file was intentional and has never been published on archive.ubuntu.com.

**To Reproduce**
Create a pulp_deb repository mirroring the remote archive.ubuntu.com

**Expected behavior**
The sync succeeds

**Repository**

```json
{
    "pulp_href": "[/pulp/api/v3/repositories/deb/apt/906ee045-9644-4d8b-9334-c6951ccffd27/](http://se-ci-apt-mirror.localdomain:24817/pulp/api/v3/repositories/deb/apt/906ee045-9644-4d8b-9334-c6951ccffd27/)",
    "pulp_created": "2021-05-21T10:47:11.342552Z",
    "versions_href": "/pulp/api/v3/repositories/deb/apt/906ee045-9644-4d8b-9334-c6951ccffd27/versions/",
    "pulp_labels": {},
    "latest_version_href": "[/pulp/api/v3/repositories/deb/apt/906ee045-9644-4d8b-9334-c6951ccffd27/versions/](http://se-ci-apt-mirror.localdomain:24817/pulp/api/v3/repositories/deb/apt/906ee045-9644-4d8b-9334-c6951ccffd27/versions/)954/",
    "name": "focal-updates.focal.no.archive.ubuntu.com",
    "description": null,
    "retained_versions": null,
    "remote": null
}
```

**Remote**

```json
{
    "pulp_href": "[/pulp/api/v3/remotes/deb/apt/5bcf4b1c-8baf-45a4-9643-dec0ce66a90b/](http://se-ci-apt-mirror.localdomain:24817/pulp/api/v3/remotes/deb/apt/5bcf4b1c-8baf-45a4-9643-dec0ce66a90b/)",
    "pulp_created": "2021-05-21T10:47:11.201264Z",
    "name": "[focal-updates.focal.no.archive.ubuntu.com](http://focal-updates.focal.no.archive.ubuntu.com/)",
    "url": "http://no.archive.ubuntu.com/ubuntu",
    "ca_cert": null,
    "client_cert": null,
    "tls_validation": true,
    "proxy_url": null,
    "pulp_labels": {},
    "pulp_last_updated": "2021-05-21T10:47:11.201279Z",
    "download_concurrency": 2,
    "policy": "immediate",
    "total_timeout": null,
    "connect_timeout": null,
    "sock_connect_timeout": null,
    "sock_read_timeout": null,
    "headers": null,
    "rate_limit": null,
    "distributions": "focal-updates",
    "components": null,
    "architectures": "amd64",
    "sync_sources": false,
    "sync_udebs": false,
    "sync_installer": false,
    "gpgkey": null,
    "ignore_missing_package_indices": false
}
```

**Comment by quba42** [comment] 2022-06-01 09:23
@knzivid If I remember correctly, the error you encountered can happen in at least the following situations:

* The remote has bad input data in the `components` field, given your components field is `null` above this is not the case here.
* The repo you are syncing from is a partial mirror where the Release/InRelease file (http://no.archive.ubuntu.com/ubuntu/dists/focal-updates/InRelease) references certain components that don't actually exist on the mirror. In this case you can set `"ignore_missing_package_indices": true` on your remote to simply ignore the error. Starting with pulp_deb 2.17.0, you can force this behaviour for all syncs by placing the `FORCE_IGNORE_MISSING_PACKAGE_INDICES = true` setting in your Pulp config file (normally `/etc/pulp/settings.py`)

**Comment by quba42** [comment] 2023-08-23 14:17
I am closing this issue, because we believe there are workarounds and it can't be reliably reproduced.

**Closed by quba42** 2023-08-23 14:17 UTC
Labels: Triage-Needed
